Ken/did merge
SeanTAllen/hcsshim pull request #36
Opened 2022-11-14 17:00 UTC by KenGordon

Fragment passing, COSE_Sign1 and DID:x509 support.

When a fragment arrives at gcs its signature is checked and the issuer DID:x509 is checked. If both are good the issuer/feed are offered to the policy and if itis accepted by the policy it will be consumed.

2022-11-18 10:06 UTC, matajoh commented
`.ls` doesn't seem to do anything?

2022-11-18 14:33 UTC, matajoh requested changes
Almost everything here is a Go style comment, overall this looks good. There are a few things that look like they are debug holdovers which probably should be dealt with.

2022-11-18 14:33 UTC, matajoh commented on internal/did-x509-resolver/resolver_test.go
> +func loadCertificateChain(t *testing.T, path string) string {
As I mentioned elsewhere, you can use `embed` to do this really cleanly.

2022-11-18 14:33 UTC, matajoh commented on internal/guest/runtime/hcsv2/uvm.go
> +	_ = didDoc
what is the purpose of this line?

2022-11-18 14:33 UTC, matajoh commented on internal/guest/runtime/hcsv2/uvm.go
> +	_ = os.WriteFile("/tmp/fragment.blob", blob, 0644)
Why are we writing a temporary file?

2022-11-18 14:33 UTC, matajoh commented on internal/guest/runtime/hcsv2/uvm.go
> +	unpacked, err = cosesign1.UnpackAndValidateCOSE1CertChain(raw, nil, nil, true)
:=

2022-11-18 14:33 UTC, matajoh commented on internal/guest/runtime/hcsv2/uvm.go
> +		var payloadString = string(unpacked.Payload[:])
:=
and the ones below

2022-11-18 14:33 UTC, matajoh commented on internal/guest/runtime/hcsv2/uvm.go
> +		var didMatchesChain, err = checkDIDvsChain(issuer, unpacked)
:=

2022-11-18 14:33 UTC, matajoh commented on internal/guest/runtime/hcsv2/uvm.go
> +	} else {
Don't need this else.

2022-11-18 14:33 UTC, matajoh commented on internal/guest/runtime/hcsv2/uvm.go
> +		if len(encodedPolicy) > 0 {
What is motivating this change?

2022-11-18 14:33 UTC, matajoh commented on internal/oci/uvm.go
> +			When adding an option here which must match some security policy by default, make sure that the correct default (ie matches
Is there a way to make this enforced by structure instead of as a comment?

2022-11-18 14:33 UTC, matajoh commented on internal/tools/sign1util/main.go
> +	var payloadBlob = cosesign1.ReadBlob(payloadFilename)
:=

2022-11-18 15:21 UTC, SeanTAllen commented on internal/cosesign1/Makefile
> +# This makefile let's us excercise the libray via the sign1util tool and shows various examples of
```suggestion
# This makefile let's us exercise the library via the sign1util tool and shows various examples of
```

2022-11-18 15:22 UTC, SeanTAllen commented on internal/cosesign1/Makefile
> +# Note that today the PEM files that match are not checked in as the credential checker will trigger.
what is the "credential checker"? starting from the Makefile, I have no idea what that is.

2022-11-18 15:23 UTC, SeanTAllen commented on internal/cosesign1/Makefile
> +# I may fix that with some head/tail magic./ Meanwhile you need to build fresh certs with make -f Makefile.certs
Fix what?What is the "that? being referenced here?

2022-11-18 15:23 UTC, SeanTAllen commented on internal/cosesign1/Makefile
> +# I may fix that with some head/tail magic./ Meanwhile you need to build fresh certs with make -f Makefile.certs
```suggestion
# I may fix that with some head/tail magic. Meanwhile you need to build fresh certs with make -f Makefile.certs
```

2022-11-18 15:24 UTC, SeanTAllen commented on internal/cosesign1/Makefile
> +# and these checks below (for infra.rego.cose, not the EPRS one) will fail.
I don't understand this comment, if I have fresh certs, the checks will fail? Am I reading that correctly?

2022-11-18 15:24 UTC, SeanTAllen commented on internal/cosesign1/Makefile
> +# from Maksim, these media types have to match containerd. The also need to change and the security policy one ought to be x-ms-ccepolicy-frag
Is there a reason to call out the particular person these came from?

2022-11-18 15:26 UTC, SeanTAllen commented on internal/cosesign1/Makefile
> +# Use a local linux build of the tool. Usually this is an exe in /mnt/c/ContainerPlat aka c:\ContainerPlat
This reads like "the local linux build is usually an exe". I don't think that is what you mean. But I'm looking at the comment and the rule and I'm somewhat confused by what the intent is. 

This is a Makefile so I would assume it only runs in Linux not Windows. Is that not the case?

2022-11-18 15:27 UTC, SeanTAllen commented on internal/cosesign1/check.go
> +// object to convey results to the caller.
I dont think this comment is very helpful.

If it is about the type below, it shouldnt have the blank line inbetween.

The GCS standard would be something like 

// UnpackedCoseSign1 is ...

2022-11-18 15:28 UTC, SeanTAllen commented on internal/cosesign1/check.go
> +	return reflect.TypeOf(val).String() == "string"
Yup.

2022-11-18 15:29 UTC, SeanTAllen commented on internal/cosesign1/check.go
> +// in the single cert case.
Is this comment about multiple methods or just the isADerChain?

I think it would be good to clarify.

2022-11-18 15:31 UTC, SeanTAllen commented on internal/cosesign1/check.go
> +	chainDER, chainPresent := protected[cose.HeaderLabelX5Chain] // The spec says this is ordered - leaf, intermediates, root. X5Bag is unordered and woould need sorting
someone will complain about this comment after the line. should move to above it.

2022-11-18 15:31 UTC, SeanTAllen commented on internal/cosesign1/check.go
> +	chainDER, chainPresent := protected[cose.HeaderLabelX5Chain] // The spec says this is ordered - leaf, intermediates, root. X5Bag is unordered and woould need sorting
```suggestion
	chainDER, chainPresent := protected[cose.HeaderLabelX5Chain] // The spec says this is ordered - leaf, intermediates, root. X5Bag is unordered and would need sorting
```

2022-11-18 15:32 UTC, SeanTAllen commented on internal/cosesign1/check.go
> +func isADEROnly(val interface{}) bool {
I think these would read easier as "isDerOnly"

the ADER reads weird

2022-11-18 15:32 UTC, SeanTAllen commented on internal/cosesign1/check.go
> +
```suggestion
```

2022-11-18 15:34 UTC, SeanTAllen commented on internal/cosesign1/check.go
> +	for i := range chainIA {
range returns two things, the index and the item. instead of using the index you can do

for _, chain : range chainIA {

}

then use chain instead of chainIA[i] later

2022-11-18 15:35 UTC, SeanTAllen commented on internal/cosesign1/check.go
> +	// A reasonable chain will have 1-100 elements
an explanation of how "reasonable" was arrived at here would be good. as a maintenance programmer, if I ended up here I would want to know.

2022-11-18 15:35 UTC, SeanTAllen commented on internal/cosesign1/check.go
> +
```suggestion
```

2022-11-18 15:36 UTC, SeanTAllen commented on internal/cosesign1/check.go
> +	var rootCert *x509.Certificate // x509 root cert
```suggestion
	var leafCert *x509.Certificate
	var rootCert *x509.Certificate
```

2022-11-18 15:37 UTC, SeanTAllen commented on internal/cosesign1/check.go
> +			}
i dont understand what we are doing here. We seem to assume this is the root cert. Is this a question to yourself the "is this the root cert?"

2022-11-18 15:39 UTC, SeanTAllen commented on internal/cosesign1/check.go
> +		return results, err
to "standard thing" to do here would be to do

```
return nil, err
```

2022-11-18 15:40 UTC, SeanTAllen commented on internal/cosesign1/check.go
> +		keyDer, _ = pem.Decode(optionaPubKeyPEM)
i assume the ignored value here is an error indicator. this wont get through review with a possible error not being handled.

2022-11-18 15:41 UTC, SeanTAllen commented on internal/cosesign1/check.go
> +				return results, err
shouldnt this be

return nil, err

?

2022-11-18 15:43 UTC, SeanTAllen commented on internal/cosesign1/check.go
> +	chainDER, chainPresent := protected[cose.HeaderLabelX5Chain] // The spec says this is ordered - leaf, intermediates, root. X5Bag is unordered and woould need sorting
you will be asked to change this from `chainPresent` to `ok` which is the standard go pattern.

<img width="822" alt="image" src="https://user-images.githubusercontent.com/193596/202743997-686eb5f1-123b-4a8f-951d-22434179b61d.png">

2022-11-18 15:43 UTC, SeanTAllen commented on internal/cosesign1/check.go
> +	}
```suggestion
	for _, c := range chainIA {
		cert, err := x509.ParseCertificate(c.([]byte))
		if err != nil {
			return err
		}
		fmt.Println(x509ToPEM(cert))
	}
```

2022-11-18 15:44 UTC, SeanTAllen commented on internal/cosesign1/cosesign1util_test.go
> +//go:build linux
same question

2022-11-18 15:47 UTC, SeanTAllen commented on internal/cosesign1/cosesign1util_test.go
> +}
This seems like a bad interface.

So if there's an error, it will return "something" for content, it will then print something to stdout and return the something that might be `nil`.

then readFileString will take that nil and do string(nil) on it. which will be a runtime error.

2022-11-18 15:48 UTC, SeanTAllen commented on internal/cosesign1/cosesign1util_test.go
> +var FragmentRego string
my capitalizing, you are exporting.

`var fragmentRego` will not export it.

2022-11-18 15:49 UTC, SeanTAllen commented on internal/cosesign1/cosesign1util_test.go
> +
This isnt the GCS standard for commenting functions.

You want something along the lines of this pattern

```
// NewSecurityPolicy creates a new SecurityPolicy from the provided values.
func NewSecurityPolicy(allowAll bool, containers []*Container) *SecurityPolicy {
```

2022-11-18 15:50 UTC, SeanTAllen commented on internal/cosesign1/check.go
> +	for which, cert := range chain {
calling the index "which" goes against standard go patterns. I have been asked to change to `i` or `index` when I did this.

2022-11-18 15:52 UTC, SeanTAllen commented on internal/cosesign1/cosesign1util_test.go
> +	var cty = unpacked.ContentType
more idomatic (you can apply this elsewhere as well)
```suggestion
	iss := unpacked.Issuer
	feed := unpacked.Feed
	pubkey := base64PublicKeyToPEM(unpacked.Pubkey)
	pubcert := base64CertToPEM(unpacked.Pubcert)
	payload := string(unpacked.Payload[:])
	cty := unpacked.ContentType
```

2022-11-18 15:54 UTC, SeanTAllen commented on internal/cosesign1/cosesign1util_test.go
> +	}
to copy an array by value you can do:

```suggestion
    FragmentCose2 = FragmentCose
```

2022-11-18 15:58 UTC, SeanTAllen commented on internal/cosesign1/cosesign1util_test.go
> +	cose := readFileBytes(filename)
see earlier comments about `readFileBytes`

2022-11-18 15:58 UTC, SeanTAllen commented on internal/cosesign1/cosesign1util_test.go
> +	FragmentRego = readFileString("infra.rego.base64")
embed is awesome

2022-11-18 15:59 UTC, SeanTAllen commented on internal/cosesign1/cosesign1util_test.go
> +	FragmentRego = readFileString("infra.rego.base64")
And it should solve all the readFileString is error prone issues.

2022-11-18 16:01 UTC, SeanTAllen commented on internal/cosesign1/create.go
> +	var chainDERArray [][]byte
This is a by value copy yes?

If so:

`chainDERArray := cert.Raw`

will do the job.

2022-11-18 16:02 UTC, SeanTAllen commented on internal/cosesign1/infra.rego
> +svn := "1.0.0"
1.0.0is in the future, this should be using an existing svn where the required functionality exists.

2022-11-18 16:04 UTC, SeanTAllen commented on internal/cosesign1/makedidx509.go
> +	_, err = didx509resolver.Resolve(chainPEM, r, true)
what is the ignored value here?

2022-11-18 16:11 UTC, SeanTAllen commented on internal/cosesign1/misc.go
> +func ReadString(path string) string {
this is an odd name. I would expect it to read a file and return a string.

2022-11-18 16:12 UTC, SeanTAllen commented on internal/cosesign1/misc.go
> +	str := string(content[:])
: isnt needed for the "all of it" case.

2022-11-18 16:12 UTC, SeanTAllen commented on internal/cosesign1/misc.go
> +
```suggestion
```

2022-11-22 10:34 UTC, KenGordon commented on internal/cosesign1/check.go
> +	if verbose {
The "print" cmd is essential "check" with verbose set. That is orthogonal to something like setting logging to debug.

2022-11-22 11:02 UTC, KenGordon commented on internal/cosesign1/create.go
> +	if err == nil {
I am going to ignore the verbose vs logging for now as I am not sure. I have to think about it (which is extra user info vs debugging of the code) whereas the rest of the changes definitely need doing.

2022-11-22 11:07 UTC, KenGordon commented on internal/cosesign1/cosesign1util_test.go
> +	FragmentRego = readFileString("infra.rego.base64")
It was embed before but Christoph didn't like me mangling the private key to avoid being shouted at by the credential daemons. That might be why the variables were capitalized. I might move it back so I can do byte by byte checks on "is this the same as before" but then I have the key storage problem. The files in question are currently built on demand so embed will not work as it will not compile.

2022-11-22 11:19 UTC, KenGordon commented on internal/cosesign1/makedidx509.go
> +	r := "did:x509:0:" + fingerprintAlgorithm + ":" + fingerprint + "::" + strings.Join(policyTokens, ":")
Now you are pulling my leg :) Are you sure?

2022-11-22 11:22 UTC, KenGordon commented on internal/cosesign1/check.go
> +	if verbose {
See later comment - I will think about this but probably not right now.

2022-11-22 12:06 UTC, KenGordon commented on internal/cosesign1/misc.go
> +func ReadBlob(path string) []byte {
These are helper function used in various places and particularly in sign1util which is not in the package.

2022-11-22 12:35 UTC, KenGordon commented on internal/did-x509-resolver/resolver.go
> +			if len(args) == 0 || len(args)%2 != 0 {
This is Christoph's and I don't think the effort of checking with him if the error messages are supposed to match some other implementation etc is worth saving the check.

2022-11-22 12:49 UTC, KenGordon commented on internal/guest/runtime/hcsv2/uvm.go
> +	_ = didDoc
Resolve returns a did document and an error. This makes reading it make more sense to the reader. I understand it is go so making sense to the reader isn't what they want so I have done away with it. I have also got rid of the whole method as the workaround it implemented is no longer needed. The fragment injection code calls the resolver itself.

2022-11-22 12:58 UTC, KenGordon commented on internal/guest/runtime/hcsv2/uvm.go
> +	_ = os.WriteFile("/tmp/fragment.blob", blob, 0644)
To check the truth of the fragment by connecting to the UVM. I know they have a fundamentalist opinion about making it hard to debug stuff but we need this for now. I have added a comment.

There is an argument to actually keep all fragments, offered, accepted, rejected, someplace a container can look at them, or way to discover your "effective" policy. I suspect Sylvan would argue against on the grounds of it being interesting but not necessarily always the truth in the face of a host passing in a fragment for a malicious container.

2022-11-22 12:59 UTC, KenGordon commented on internal/guest/runtime/hcsv2/uvm.go
> +	unpacked, err = cosesign1.UnpackAndValidateCOSE1CertChain(raw, nil, nil, true)
ok, but it makes it less readable....

2022-11-22 13:01 UTC, KenGordon commented on internal/guest/runtime/hcsv2/uvm.go
> +		var payloadString = string(unpacked.Payload[:])
So, given the language clearly supports var fred = blah() what is the justification for insisting on using :=?

2022-11-22 13:03 UTC, KenGordon commented on internal/guest/runtime/hcsv2/uvm.go
> +		var didMatchesChain, err = checkDIDvsChain(issuer, unpacked)
Gone

2022-11-22 13:14 UTC, KenGordon commented on internal/oci/uvm.go
> +			When adding an option here which must match some security policy by default, make sure that the correct default (ie matches
Not practically. I guess you could have some json that described possible annotations and their dependency graph and the use that to generate all this code but really...

2022-11-22 13:16 UTC, KenGordon commented on internal/cosesign1/Makefile
> +# Note that today the PEM files that match are not checked in as the credential checker will trigger.
The github/ADO thing that spots when you commit credentials or secrets into a repo.

2022-11-22 13:17 UTC, KenGordon commented on internal/cosesign1/Makefile
> +# I may fix that with some head/tail magic./ Meanwhile you need to build fresh certs with make -f Makefile.certs
The noticing that a thing is a private key.

2022-11-22 13:26 UTC, KenGordon commented on internal/cosesign1/Makefile
> +# and these checks below (for infra.rego.cose, not the EPRS one) will fail.
Yes. I have added explanation and instructions.

Basically, we can't have stable private certs because github etc. You need some certs but the checks in the makefile will not match. This makefile, as it stands, is extremely useful to me and likely to be helpful to people trying to use the tool.

2022-11-22 13:31 UTC, KenGordon commented on internal/cosesign1/Makefile
> +# Use a local linux build of the tool. Usually this is an exe in /mnt/c/ContainerPlat aka c:\ContainerPlat
I have made it clearer. The tool was previously always an exe but for the purposes of this Makefile it is build as an a.out style linux binary.

2022-11-22 13:42 UTC, KenGordon commented on internal/cosesign1/check.go
> +			}
I have updated the comment so be sure of itself.

2022-11-22 13:45 UTC, KenGordon commented on internal/cosesign1/check.go
> +		keyDer, _ = pem.Decode(optionaPubKeyPEM)
keyDer, _ = pem.Decode(optionalPubKeyPEM) // _ is the remaining. We only care about the first key.

See, they want their cake (obscure code that doesn't have unused variables, and to eat it - be readable. :)

2022-11-22 14:03 UTC, wintersteiger commented on internal/cosesign1/makedidx509.go
> +	_, err = didx509resolver.Resolve(chainPEM, r, true)
The DID document; required byt he DID spec, but useless in our use-case here.

2022-11-22 14:21 UTC, wintersteiger commented on internal/cosesign1/cosesign1util_test.go
> +	FragmentRego = readFileString("infra.rego.base64")
Yes, I removed that because we shouldn't check in any private keys. Various people will complain, regardless of whether the keys belong to someone or whether they are random. Just much less friction to generate new keys during test runs and not a lot of effort either. My only problem is that I don't know how to use Go, so currently this still calls out to `make`; we should perhaps change that to call out to the `openssl` binary (multiple times), which would also work on Windows as long as OpenSSL is installed.

2022-11-22 14:26 UTC, wintersteiger commented on internal/cosesign1/makedidx509.go
> +// The x509 package/module doesn't export these...
No information on that topic, but the OIDs are fixed, they could only change the (Go) names (and we can keep using ours...).

2022-11-22 14:33 UTC, wintersteiger commented on internal/cosesign1/makedidx509.go
> +	r := "did:x509:0:" + fingerprintAlgorithm + ":" + fingerprint + "::" + strings.Join(policyTokens, ":")
Seriously? I would not have expected that to be the preferred Go style, but feel free to change it.

2022-11-22 14:39 UTC, wintersteiger commented on internal/guest/runtime/hcsv2/uvm.go
> +		var payloadString = string(unpacked.Payload[:])
Yeah, I'm not totally sure about that either. I can see `var ... = ..` being used frequently in other libraries/packages too, e.g. x509.

2022-11-22 14:44 UTC, wintersteiger commented on internal/cosesign1/check.go
> +	// A reasonable chain will have 1-100 elements
I think we could remove that check entirely. There's no inherent problem with huge chains, it will just take longer to check them.

2022-11-22 14:46 UTC, KenGordon commented on internal/cosesign1/infra.rego
> +svn := "1.0.0"
Isn't this the SVN of my infra container?

2022-11-22 14:51 UTC, KenGordon commented on internal/cosesign1/misc.go
> +func ReadString(path string) string {
I have changed path to filename

2022-11-22 15:00 UTC, KenGordon commented on internal/cosesign1/misc.go
> +// to replace the rand.Reader with a fixed salt to make debugging easier.
Less random randomness:
// Type to replace the rand.Reader with a source of fixed salt.
// Can be provided to the cose.Sign1 method instead of rand.Reader such that
// the signature is deterministic for testing and debugging purposes.

2022-11-22 15:19 UTC, KenGordon commented on internal/cosesign1/cosesign1util_test.go
> +	}
Are you sure this does a value copy? I need not to change the source one and I am about to zap bytes in the copy.

2022-11-22 15:19 UTC, KenGordon commented on internal/cosesign1/cosesign1util_test.go
> +	}
seems I needed 
	copy(fragCose, fragmentCose)

2022-11-23 13:39 UTC, KenGordon commented
Squash all the commits to tidy the signing issue.

2022-11-23 13:39 UTC, closed without merging