Process logging enforcement
SeanTAllen/hcsshim pull request #37
Opened 2022-11-18 18:22 UTC by SeanTAllen

2022-11-18 18:29 UTC, SeanTAllen commented on pkg/securitypolicy/open_door.rego
> +scratch_unmount := {"allowed": true}
im not sure why this is in here, @matajoh any ideas?

2022-11-18 18:31 UTC, SeanTAllen commented on pkg/securitypolicy/securitypolicyenforcer_rego.go
> +	return toKeep, err
im also not sure how this ended up in here.

2022-11-21 09:42 UTC, matajoh reviewed
Just a few small things.

2022-11-21 09:42 UTC, matajoh commented on pkg/securitypolicy/open_door.rego
> +scratch_unmount := {"allowed": true}
They were missing previously, I don't believe they were added when Maksim did his PR for encrypted scratch. They are rules that need to be present, as they are present in the `policy.rego`.

2022-11-21 09:42 UTC, matajoh commented on pkg/securitypolicy/securitypolicy_internal.go
> +	AllowStdioAccess bool
Nit: why is this exported when other things are not? I feel we should be consistent.

2022-11-21 09:42 UTC, matajoh commented on pkg/securitypolicy/securitypolicy_internal.go
> +		AllowStdioAccess: p.AllowStdioAccess,
Same comment re: consistency.

2022-11-21 09:42 UTC, matajoh commented on pkg/securitypolicy/securitypolicyenforcer_rego.go
> +	return toKeep, err
This must have been a rebase error on my part.

2022-11-21 09:42 UTC, matajoh commented on pkg/securitypolicy/securitypolicyenforcer_rego.go
> +	return toKeep, stdioAccessAllowed, err
This must have been a rebase error as well, *i.e.* this should be `nil` instead of `err` as well

2022-11-29 02:27 UTC, anmaxvl requested changes

2022-11-29 02:27 UTC, anmaxvl commented on internal/guest/runtime/hcsv2/uvm.go
> +		if params.OCIProcess.Terminal && !allowStdioAccess {
for external process `params.OCIProcess` is `nil`. You'd need to check against `params.CreateStdInPipe` instead.

2022-11-29 02:27 UTC, anmaxvl commented on internal/guest/runtime/hcsv2/uvm.go
> +			return pid, errors.Wrapf(err, "exec of process that requires terminal access denied due to policy not allowing stdio access")
same issue with wrapping a `nil` error like below.

2022-11-29 13:38 UTC, SeanTAllen commented on internal/guest/runtime/hcsv2/uvm.go
> +	devNullTransport transport.Transport
i dont know what you mean.

2022-11-29 13:41 UTC, SeanTAllen commented on internal/guest/runtime/hcsv2/uvm.go
> +				return pid, errors.Wrapf(err, "exec in container of process that requires terminal access denied due to policy not allowing stdio access")
fixed.

2022-11-29 13:42 UTC, SeanTAllen commented on internal/guest/runtime/hcsv2/uvm.go
> +		if params.OCIProcess.Terminal && !allowStdioAccess {
fixed.

2022-11-29 13:42 UTC, SeanTAllen commented on internal/guest/runtime/hcsv2/uvm.go
> +			return pid, errors.Wrapf(err, "exec of process that requires terminal access denied due to policy not allowing stdio access")
fixed.

2022-11-29 13:43 UTC, SeanTAllen commented on internal/guest/transport/devnull.go
> +	read  *os.File
No. We covered this last week on a call. The protocol expects a duplex connection and we need to act accordingly.

2022-11-29 13:45 UTC, SeanTAllen commented on internal/guest/transport/devnull.go
> +	read  *os.File
I originally had read as no file handle and handled it all myself in code but that required even more state and was more error prone to make sure the correct result was returned.

2022-11-29 13:45 UTC, SeanTAllen commented on internal/guest/transport/devnull.go
> +	read  *os.File
I'm adding the documentation for devnull now.

2022-11-30 00:36 UTC, helsaawy reviewed
I think this is ready for general review, though I think the `DevNullTransport` may be contentious.
`stdio.ConnectionSet` and `stdio.Connect` both probably need an overhaul, since users dont really need the full `transport.Connection`, and probably just a file or regular `net.Conn` would do...

2022-11-30 00:36 UTC, helsaawy commented on internal/guest/transport/devnull.go
> +	return f, nil
Given the above discussion,I think it would also work to simply
```go
	return nil, errors.New("devNullConnection does not support File()")
```
That way, we can track down and audit and instances that expect `File` to work, so we dont end up with weird side effects from expecting it to work a certain way

2022-11-30 00:36 UTC, helsaawy commented on internal/guest/transport/devnull.go
> +	return f, nil
An alternative approach would be to open both `c.read` and `c.write` for `os.O_RDWR`, and then in [`stdio.Connect`](https://github.com/microsoft/hcsshim/blob/main/internal/guest/stdio/connection.go#L68), check if the connections are of type `devNullConnection` and, if they are, tell then if they are being used for stdin or stdout/err, so they can return the appropriate end from `File`

2022-11-30 17:31 UTC, anmaxvl commented on internal/guest/runtime/hcsv2/uvm.go
> +	devNullTransport transport.Transport
the alternative would be to define a singleton for devNullTransport in its package, right? I just don't see the need for it to be part of the `Host` struct.

2022-11-30 17:34 UTC, anmaxvl commented on internal/guest/runtime/hcsv2/uvm.go
> +		var transport = h.vsock
can you rename the variable? we are importing a package `github.com/Microsoft/hcsshim/internal/guest/transport` and if someone tries to use it in this function below, they'll get an error, because the name has been overwritten.

2022-11-30 17:35 UTC, anmaxvl commented on internal/guest/runtime/hcsv2/uvm.go
> +	transport transport.Transport,
same here, this collides with the imported package.

2022-11-30 18:51 UTC, SeanTAllen commented on internal/guest/runtime/hcsv2/uvm.go
> +	devNullTransport transport.Transport
I think consistency with vsock setup is important. I think you could make the statement about vsock. However, I think making that change is outside the scope of this PR.

2022-11-30 18:52 UTC, SeanTAllen commented on internal/guest/transport/devnull.go
> +	w, _ := os.OpenFile(os.DevNull, os.O_WRONLY, 0)
if they do, the world is throughly messed up.

2022-11-30 18:53 UTC, SeanTAllen commented on internal/guest/transport/devnull.go
> +	return f, nil
If someone wants to do a large scale refactor, I think that is outside the scope of this functionality.

2022-12-02 17:45 UTC, closed without merging